# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "CSSConf Australia 2016"
email: "team@cssconf.com.au"
sponsors_email: "sponsors@cssconf.com.au"
description: "A one day conference bringing together the designers and developers of the future of the web."
baseurl: ""
url: ""
ticket_url: "http://ti.to/cssconf-au/2016/"
jsconf_url: "http://2016.jsconfau.com"
cssconf_url: "http://2016.cssconf.com.au"
decompress_url: "http://decompress.com.au"

collections:
  - team

# Build settings
markdown: kramdown
exclude: [vendor]
